//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "actions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub action_type: String,
    #[sea_orm(column_type = "Text")]
    pub entity: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub attribute: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub value_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub value_id: Option<String>,
    pub number_value: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub string_value: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub entity_value: Option<String>,
    pub array_value: Option<Vec<String>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
