//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "entity_attributes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub entity_id: String,
    #[sea_orm(column_type = "Text")]
    pub attribute_of: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::entities::Entity",
        from = "Column::EntityId",
        to = "super::entities::Column::Id"
    )]
    Entities,
    #[sea_orm(
        belongs_to = "super::entities::Entity",
        from = "Column::AttributeOf",
        to = "super::entities::Column::Id"
    )]
    AttributeOf,
}

impl ActiveModelBehavior for ActiveModel {}
