//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "log_entries")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    pub created_at_block: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub uri: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub created_by: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub space: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub mime_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub decoded: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub json: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
