//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::cursors::Entity as Cursors;
pub use super::entities::Entity as Entities;
pub use super::entity_attributes::Entity as EntityAttributes;
pub use super::spaces::Entity as Spaces;
pub use super::triples::Entity as Triples;
