//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::accounts::Entity as Accounts;
pub use super::actions::Entity as Actions;
pub use super::cursors::Entity as Cursors;
pub use super::entities::Entity as Entities;
pub use super::entity_attributes::Entity as EntityAttributes;
pub use super::entity_types::Entity as EntityTypes;
pub use super::log_entries::Entity as LogEntries;
pub use super::proposals::Entity as Proposals;
pub use super::proposed_versions::Entity as ProposedVersions;
pub use super::spaces::Entity as Spaces;
pub use super::triples::Entity as Triples;
pub use super::versions::Entity as Versions;
