//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "spaces")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub address: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub created_at_block: Option<String>,
    pub is_root_space: Option<bool>,
    #[sea_orm(column_type = "Text", nullable)]
    pub admins: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub editor_controllers: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub editors: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub entity: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
