//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "triples")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub entity_id: String,
    #[sea_orm(column_type = "Text")]
    pub attribute_id: String,
    #[sea_orm(column_type = "Text")]
    pub value_id: String,
    #[sea_orm(column_type = "Text")]
    pub value_type: String,
    #[sea_orm(column_type = "Text")]
    pub defined_in: String,
    pub is_protected: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub number_value: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub array_value: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub string_value: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub entity_value: Option<String>,
    pub deleted: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
